- name: update linux settings for network performance
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0644
  tags: ['sysctl-config']

- name: reload sysctl.conf
  command: /sbin/sysctl -p /etc/sysctl.conf
  tags: ['sysctl-config']
