- name: Add new sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
  tags: sshd-config

- name: Restart SSH
  service:
    name: ssh
    state: restarted
  tags: sshd-config
